#!/usr/bin/env python
"""
docs
"""
from __future__ import absolute_import, print_function
import os
import sys
import time
import json

import logging
logger = logging.basicConfig(level=logging.WARN)

from requests.packages import urllib3
urllib3.disable_warnings()

from tweepy import OAuthHandler
from tweepy import Stream
from twapture import SerializedListener, Statistics

# Go to http://apps.twitter.com and create an app.
# The consumer key and secret will be generated for you after
consumer_key=os.environ['TWITTER_CONSUMER_KEY']
consumer_secret=os.environ['TWITTER_CONSUMER_SECRET']

# After the step above, you will be redirected to your app's page.
# Create an access token under the the "Your access token" section
access_token=os.environ['TWITTER_ACCESS_TOKEN']
access_token_secret=os.environ['TWITTER_ACCESS_TOKEN_SECRET']


def main():

    # Give the user indication of what's happening
    sys.stderr.write('Starting statistic collection at %s.\n' % time.ctime())
    sys.stderr.write('Use Ctrl-C to write report.\n\n')

    # add the stat classifier to the callback list
    stats = Statistics(filename='stdout', format='raw', interval='20s')
    listener = SerializedListener(stats.status_handler)

    auth = OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_token_secret)
    stream = Stream(auth, listener)

    try:
        #stream.filter(locations=[-90.0,24.0, -86.0,50.0])
        #stream.filter(locations="-90.0,24.0, -86.0,50.0")
        stream.filter(track="Chicago")
        #stream.filter(track="Chicago, Dallas")
        #stream.filter(track=["Chicago", "Dallas"])

    except KeyboardInterrupt: 
        stats.report() 

    except Exception as e:
        logger.exception('filter exception %s', e)


if __name__ == '__main__':
    main()

